export const TEXTS = {
  ru: {
    under_balance: 'Общий баланс в',
    pay_in: 'Пополнить',
    pay_out: 'Вывести',
    transfer: 'Перевести',
    my_actives: 'Активы',
    payin_history: 'Пополнения',
    payout_history: 'Выводы',
    one_payin: 'Пополнение',
    one_transfer: 'Внутренний перевод',
    one_payout: 'Вывод',
    one_exchange: 'Обмен',
    stockMarket: 'Маркет ордер',
    stockLimit: 'Лимитный ордер',
    // one_transferTo: 'Перевод юзеру',
    textBalanceZero: 'Ваш баланс равен 0',
    noPay: 'не было операций',
    tryLaterText : 'Сервис временно недоступен, попробуйте позже',
  },
  en: {
    under_balance: 'Total balance in',
    pay_in: 'Deposit',
    pay_out: 'Withdraw',
    transfer: 'Transfer',
    my_actives: 'Assets',
    payin_history: 'Deposits',
    payout_history: 'Withdrawals',
    one_payin: 'Deposit',
    one_transfer: 'In app transfer',
    one_payout: 'Withdraw',
    one_exchange: 'Exchange',
    stockMarket: 'Market order',
    stockLimit: 'Limit order',
    // one_transferTo: 'Transfer to user',
    textBalanceZero: 'Your balance is 0',
    noPay: 'were not performed',
    tryLaterText : 'App is not available at the moment, please try later',
    
  },
  de: {
    under_balance: 'Gesamtsaldo in', 
    pay_in: 'Einzahlung',
    pay_out: 'Zurückziehen',
    transfer: 'Übertragung',
    my_actives: 'Vermögenswerte',
    payin_history: 'Einlagen',
    payout_history: 'Abhebungen',
    one_payin: 'Kaution',
    one_transfer: 'In-App-Übertragung',
    one_payout: 'Zurückziehen',
    one_exchange: 'Austausch',
    stockMarket: 'Marktorder',
    stockLimit: 'Limit-Order',
    // one_transferTo: 'Geldüberweisung an Benutzer',
    textBalanceZero: 'Ihr Saldo ist 0',
    noPay: 'wurden nicht durchgeführt',
    tryLaterText : 'Die App ist derzeit nicht verfügbar. Bitte versuchen Sie es später erneut.',
  },
};


  