export const TEXTS = {
  ru: {
    title: 'Обмен криптовалюты',
    header1: 'Вы платите',
    wordMaximum: 'Максимум: ',
    swapText: 'поменять',
    youGetText: 'Вы получате',
    title2From: 'Валюта для обмена',
    title2To: 'Валюта в которую переводим',
    minsum: 'Минимальная сумма пополнения',
    errorSumTooBig: 'Сумма больше вашего баланса',
    errorMinSumBig: 'нельзя меньше минимальной суммы',
    nextBtn: 'Проверить сделку',
    cnfBtn: 'Подтвердить и обменять',
    success: 'Успешно',
    exchangeTitle: 'Обмен завершен',
    exchangeText: 'зачислим в ближайшее время на ваш баланс',
    openWalletBtn: 'Открыть кошелек',
    
  },
  en: {
    title: 'Exchange cryptocurrency',
    header1: 'You pay',
    wordMaximum: 'Max: ',
    swapText: 'swap',
    youGetText: 'You get',
    title2From: 'Currency to be exchanged',
    title2To: 'Currency we transfer to',
    minsum: 'Minimum sum to deposit',
    errorSumTooBig: 'Sum is bigger than your balance',
    errorMinSumBig: 'can`t be less than the minimum amount',
    nextBtn: 'Check deal',
    cnfBtn: 'Confirm and exchange',
     success: 'Success',
     exchangeTitle: 'Exchange done',
     exchangeText: 'will be credited to your balance shortly',
     openWalletBtn: 'Open wallet',
    
  },
  de: {
    title: 'Finanzierung durch Kryptowährungen',
    header1: 'Sie zahlen', 
    wordMaximum: 'Maximum: ',
    swapText: 'tauschen',
    youGetText: 'Sie erhalten',
    title2From: 'Umzutauschende währung',
    title2To: 'Währung, in die wir überweisen',
    minsum: 'Währungsumtausch',
    errorSumTooBig: 'Die Summe ist größer als Ihr Guthaben',
    errorMinSumBig: 'darf nicht geringer sein als der Mindestbetrag',
    nextBtn: 'Geschäft prüfen',
    cnfBtn: 'Bestätigen und austauschen',
    success: 'Erfolg',
     exchangeTitle: 'Austausch erfolgt',
     exchangeText: 'wird Ihrem Guthaben in Kürze gutgeschrieben',
     openWalletBtn: 'Brieftasche öffnen',
       
  },
};
