export const TEXTS = {
  ru: {
    title: 'Вывод криптовалюты',
    title2: 'Укажите адрес и сумму',
    balanceT: 'Баланс',
    comissionT: 'Комиссия',
    adressT: 'Адрес',
    adress_sub: 'укажите адрес кошелька',
    sumT: 'Сумма ',
    sumT_sub: 'укажите сумму в',
    max: 'Макс',
    nextbtn: 'Продолжить',
    errorEmpty: 'Адрес пустой',
    errorNotValid: 'Адрес не валидный',
    errorSumEpmty: 'Сумма пустая',
    errorSumTooBig: 'Сумма больше вашего баланса',
    title3: 'Подтвердите данные',
    totalSum: 'Общая сумма',
    sendText: 'Отправка',
    to: 'Кому',
    cnfBtn: 'Подтвердить',
    success: 'Успешно',
    withdrawTitle: 'Вывод',
    withdrawText: 'Монеты будут отправлены в ближайшее время',
    openWalletBtn: 'Открыть кошелек'
  },
  en: {
    title: 'Withdraw cryptocurrency',
    title2: 'Set adress and sum',
    balanceT: 'Balance',
    comissionT: 'Commission',
    adressT: 'Adress',
    adress_sub: 'set wallet adress',
    sumT: 'Sum of ',
    sumT_sub: 'set sum at',
    max: 'Max',
    nextbtn: 'Next',
    errorEmpty: 'Adress is epmty',
    errorNotValid: 'Adress is not valid',
    errorSumEpmty: 'Sum is empty',
    errorSumTooBig: 'Sum is bigger than your balance',
    title3: 'Confirmition',
    totalSum: 'Total sum',
    sendText: 'To be sent',
    to: 'To',
    cnfBtn: 'Confirm',
    success: 'Success',
    withdrawTitle: 'Withdrawed',
    withdrawText: 'Coins will be sent soon',
    openWalletBtn: 'Open wallet'
  },
  de: {
    title: 'Kryptowährung abheben',
    title2: 'Adresse und Summe einstellen',
    balanceT: 'Bilanz',
    comissionT: 'Kommission',
    adressT: 'Adresse',
    adress_sub: 'adresse der Brieftasche einstellen',
    sumT: 'Anzahl der ',
    sumT_sub: 'summe einstellen auf',
    max: 'Max',
    nextbtn: 'Weiter',
    errorEmpty: 'Adresse ist epmty',
    errorNotValid: 'Adresse ist ungültig',
    errorSumEpmty: 'Summe ist leer',
    errorSumTooBig: 'Die Summe ist größer als Ihr Guthaben',
    title3: 'Konfirmation',
    totalSum: 'Gesamtbetrag',
    sendText: 'Zu versenden',
    to: 'An wen',
    cnfBtn: 'Bestätigen Sie',
    success: 'Erfolg',
    withdrawTitle: 'Zurückgezogen',
    withdrawText: 'Die Münzen werden bald verschickt',
    openWalletBtn: 'Brieftasche öffnen'
  },
};
