export const TEXTS = {
  ru: {
    title: 'Выберите торговую пару',
    header1: 'Вы платите',
    wordMaximum: 'Макс',
    swapText: 'поменять',
    youGetText: 'Вы получате',
    title2From: 'Валюта для обмена',
    title2To: 'Валюта в которую переводим',
    minsum: 'Минимальная сумма пополнения',
    errorSumTooBig: 'Сумма больше вашего баланса',
    errorMinSumBig: 'нельзя меньше минимальной суммы',
    nextBtn: 'Проверить сделку',
    cnfBtn: 'Подтвердить и обменять',
    success: 'Успешно',
    exchangeTitle: 'Обмен завершен',
    exchangeText: 'зачислим в ближайшее время на ваш баланс',
    openWalletBtn: 'Открыть кошелек',
    minSumToExchangeText: 'мин. сумма для обмена',
    stockTitle: 'Заявка размещена на бирже',
    openStockBtn: 'Открыть биржу',
    openOrder: 'Открытые ордера',
    historyOrder: 'История ордеров ',
    tryLaterText : 'Биржа недоступна, попробуйте позже',
    btnBuyText: 'Купить',
    btnSellText: 'Продать',
    marketOrdertext: 'Маркет ордер',
    limitOrdertext: 'Лимитный ордер',
    stockPriceText: 'Рыночная цена:',
    totalText: 'Количество ',
    availableText: 'Доступно: ',
    maxBuyText: 'Максимальная покупка:',
    maxSellText: 'Максимальная продажа:',
    minSumText: 'мин. сумма',
    zeroText: 'выбран 0',
    notEnoughText: 'недостаточно монет',
    noOpenText: 'нет открытых ордеров',
    noHistoryText: 'нет истории сделок',
    priceLimitText: 'Цена',
    cnlOrderT: 'отменить ордер',
    reasonCancellingNowT: 'ордер уже отменяется, скоро деньги разморозятся',
    reasonAlreadyDoneT: 'ордер ордер уже исполнен, скоро переведем вам средства',
    reasonTryIn1minT: 'отмена будет доступна примерно через 1 минуту',
    reasonCnlReceivedT: 'отмена ордера принята в работу'
    
  },
  en: {
    title: 'Select a trading pair',
    header1: 'You pay',
    wordMaximum: 'Max',
    swapText: 'swap',
    youGetText: 'You get',
    title2From: 'Currency to be exchanged',
    title2To: 'Currency we transfer to',
    minsum: 'Minimum sum to deposit',
    errorSumTooBig: 'Sum is bigger than your balance',
    errorMinSumBig: 'can`t be less than the minimum amount',
    nextBtn: 'Check deal',
    cnfBtn: 'Confirm and exchange',
     success: 'Success',
     exchangeTitle: 'Exchange done',
     exchangeText: 'will be credited to your balance shortly',
     openWalletBtn: 'Open wallet',
     minSumToExchangeText: 'min amount to exchange',
     stockTitle: 'Your order have been placed',
     openStockBtn: 'Open crypto stock',
     openOrder: 'Open orders',
    historyOrder: 'History orders',
    tryLaterText : 'Stock is not available at the moment, please try later',
    btnBuyText: 'Buy',
    btnSellText: 'Sell',
    marketOrdertext: 'Market order',
    limitOrdertext: 'Limit order',
    stockPriceText: 'Market price:',
    totalText: 'Quantity ',
    availableText: 'Available: ',
    maxBuyText: 'Max sum to buy:',
    maxSellText: 'Max sum to sell:',
    minSumText: 'min. sum',
    zeroText: 'you choosed 0',
    notEnoughText: 'not enough coins',
    noOpenText: 'no open deal',
    noHistoryText: 'no deal history',
    priceLimitText: 'Price',
    cnlOrderT: 'cancell order',
    reasonCancellingNowT: 'the order is cancelling now and the funds will soon be unfrozen',
    reasonAlreadyDoneT: 'the order has already been fulfilled, and we will transfer the funds to you shortly',
    reasonTryIn1minT: 'cancelaltion will be availablbe in 1 minute approximately',
    reasonCnlReceivedT: 'cancellation is in progress'
    

    
    
  },
  de: {
    title: 'Wählen Sie ein Handelspaar',
    header1: 'Sie zahlen', 
    wordMaximum: 'Max',
    swapText: 'tauschen',
    youGetText: 'Sie erhalten',
    title2From: 'Umzutauschende währung',
    title2To: 'Währung, in die wir überweisen',
    minsum: 'Währungsumtausch',
    errorSumTooBig: 'Die Summe ist größer als Ihr Guthaben',
    errorMinSumBig: 'darf nicht geringer sein als der Mindestbetrag',
    nextBtn: 'Geschäft prüfen',
    cnfBtn: 'Bestätigen und austauschen',
    success: 'Erfolg',
     exchangeTitle: 'Austausch erfolgt',
     exchangeText: 'wird Ihrem Guthaben in Kürze gutgeschrieben',
     openWalletBtn: 'Brieftasche öffnen',
     minSumToExchangeText: 'mindestbetrag für den Umtausch',
     stockTitle: 'Ihre Bestellung wurde aufgegeben',
     openStockBtn: 'Krypto-Aktie eröffnen',
     openOrder: 'Offene Aufträge',
      historyOrder: 'Verlaufsbestellungen',
      tryLaterText : 'Kryptoaktien sind im Moment nicht verfügbar, bitte versuchen Sie es später',
      btnBuyText: 'Kaufen',
    btnSellText: 'Verkaufen',
    marketOrdertext: 'Marktauftrag',
    limitOrdertext: 'Limit-Order',
    stockPriceText: 'Marktpreis:',
    totalText: 'Menge ',
    availableText: 'Verfügbar: ',
     maxBuyText: 'Maximal zu kaufende Summe:',
     maxSellText: 'Maximale verkaufssumme:',
     minSumText: 'mindestbetrag',
     zeroText: 'sie haben 0 gewählt',
     notEnoughText: 'nicht genug münzen',
     noOpenText: 'kein offenes Geschäftl',
     noHistoryText: 'no-deal-geschichte',
     priceLimitText: 'Preis',
     cnlOrderT: 'bestellung stornieren',
     reasonCancellingNowT: 'die Bestellung wird jetzt storniert und die Gelder werden bald freigegeben',
     reasonAlreadyDoneT: 'die Bestellung wurde bereits ausgeführt, und wir werden Ihnen den Betrag in Kürze überweisen',
     reasonTryIn1minT: 'die Stornierung wird in etwa 1 Minute verfügbar sein',
     reasonCnlReceivedT: 'die Stornierung wird gerade durchgeführt'

       
  },
};
