export const TEXTS = {
  ru: {
    title: 'Выберите торговую пару',
    header1: 'Вы платите',
    wordMaximum: 'Макс',
    swapText: 'поменять',
    youGetText: 'Вы получате',
    title2From: 'Валюта для обмена',
    title2To: 'Валюта в которую переводим',
    minsum: 'Минимальная сумма пополнения',
    errorSumTooBig: 'Сумма больше вашего баланса',
    errorMinSumBig: 'нельзя меньше минимальной суммы',
    nextBtn: 'Проверить сделку',
    cnfBtn: 'Подтвердить и обменять',
    success: 'Успешно',
    exchangeTitle: 'Обмен завершен',
    exchangeText: 'зачислим в ближайшее время на ваш баланс',
    openWalletBtn: 'Открыть кошелек',
    minSumToExchangeText: 'мин. сумма для обмена',
    stockTitle: 'Заявка размещена на бирже',
    openStockBtn: 'Открыть биржу',
    openOrder: 'Открытые ордера',
    historyOrder: 'История ордеров ',
    tryLaterText : 'Биржа недоступна, попробуйте позже',
    btnBuyText: 'Купить',
    btnSellText: 'Продать',
    marketOrdertext: 'Маркет ордер',
    stockPriceText: 'Рыночная цена:',
    totalText: 'Всего ',
    availableText: 'Доступно: ',
    maxBuyText: 'Максимальная покупка:',
    minSumText: 'мин. сумма',
    zeroText: 'выбран 0',
    notEnoughText: 'недостаточно монет',
    
    
  },
  en: {
    title: 'Select a trading pair',
    header1: 'You pay',
    wordMaximum: 'Max',
    swapText: 'swap',
    youGetText: 'You get',
    title2From: 'Currency to be exchanged',
    title2To: 'Currency we transfer to',
    minsum: 'Minimum sum to deposit',
    errorSumTooBig: 'Sum is bigger than your balance',
    errorMinSumBig: 'can`t be less than the minimum amount',
    nextBtn: 'Check deal',
    cnfBtn: 'Confirm and exchange',
     success: 'Success',
     exchangeTitle: 'Exchange done',
     exchangeText: 'will be credited to your balance shortly',
     openWalletBtn: 'Open wallet',
     minSumToExchangeText: 'min amount to exchange',
     stockTitle: 'Your order have been placed',
     openStockBtn: 'Open crypto stock',
     openOrder: 'Open orders',
    historyOrder: 'History orders',
    tryLaterText : 'Stock is not available at the moment, please try later',
    btnBuyText: 'Buy',
    btnSellText: 'Sell',
    marketOrdertext: 'Market order',
    stockPriceText: 'Market price:',
    totalText: 'Total ',
    availableText: 'Available: ',
    maxBuyText: 'Max sum to buy:',
    minSumText: 'min. sum',
    zeroText: 'you choosed 0',
    notEnoughText: 'not enough coins',
    

    
    
  },
  de: {
    title: 'Wählen Sie ein Handelspaar',
    header1: 'Sie zahlen', 
    wordMaximum: 'Max',
    swapText: 'tauschen',
    youGetText: 'Sie erhalten',
    title2From: 'Umzutauschende währung',
    title2To: 'Währung, in die wir überweisen',
    minsum: 'Währungsumtausch',
    errorSumTooBig: 'Die Summe ist größer als Ihr Guthaben',
    errorMinSumBig: 'darf nicht geringer sein als der Mindestbetrag',
    nextBtn: 'Geschäft prüfen',
    cnfBtn: 'Bestätigen und austauschen',
    success: 'Erfolg',
     exchangeTitle: 'Austausch erfolgt',
     exchangeText: 'wird Ihrem Guthaben in Kürze gutgeschrieben',
     openWalletBtn: 'Brieftasche öffnen',
     minSumToExchangeText: 'mindestbetrag für den Umtausch',
     stockTitle: 'Ihre Bestellung wurde aufgegeben',
     openStockBtn: 'Krypto-Aktie eröffnen',
     openOrder: 'Offene Aufträge',
      historyOrder: 'Verlaufsbestellungen',
      tryLaterText : 'Kryptoaktien sind im Moment nicht verfügbar, bitte versuchen Sie es später',
      btnBuyText: 'Kaufen',
    btnSellText: 'Verkaufen',
    marketOrdertext: 'Marktauftrag',
    stockPriceText: 'Marktpreis:',
    totalText: 'Insgesamt ',
    availableText: 'Verfügbar: ',
     maxBuyText: 'Maximal zu kaufende Summe:',
     minSumText: 'mindestbetrag',
     zeroText: 'sie haben 0 gewählt',
     notEnoughText: 'nicht genug münzen'

       
  },
};
